---
- name: install picool
  hosts:
  - picool
  become: true

  tasks:

    tasks:
    - name: "Check out a Git repository on the Ansible host"
      local_action: 
        module: git
        repo: https://github.com/Smithsonite/picool.git
        dest: /git/picool/
      become: false

    - name: Install python pip globally
      apt:
        name: python3-pip
        state: present

    - name: Copy fancontrol files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: u=rwxr,g=r,o=x
      with_items:
        - src: /git/picool/fancontrol.py
          dest: /usr/local/bin/fancontrol.py
        - src: /git/picool/requirements.txt
          dest: /home/ansible/picool/
        - src: /git/picool/fancontrol.sh
          dest: /etc/init.d/fancontrol.sh
    
    - name: install picool requirements
      pip:
        requirements: /home/ansible/picool/requirements.txt

    - name: enabling the picool service
      ansible.builtin.service:
        name: "fancontrol.sh"
        enabled: yes

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot: